### ISSUE TITLE
Road to deploy app failure

### ISSUE THREAD

**Issue by slaptot** [DenisVuyka/ionic-alfresco-app#1]
Hola!
thank you for integrate alfresco-js-api with IONIC, it's awesome! But I can't do it work :( .
I would like to share with you my road to try start the project, and you could add documentation in your readme.md.

1. First of all, when I try to install packages and launch "ionic serve" get this error in gulpfile:
`There is an error in your gulpfile: 
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/alberto/CordovaDev/ionic-alfresco-app/gulpfile.js:8:25)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
`
 module "@DenisVuyka/ionic-gulp-build-typescript" file index.js should prepend "use strict"; 

2. alfresco-js-api module works on alfresco 5.2, so you should warn in your readme.md in order to get it working. Latest EarlyAccess versions "[https://wiki.alfresco.com/wiki/Community_file_list_201606-EA]

Using postman I can do login, but using the app from Chrome Browser or Hybrid App, I get 403 error:

`XMLHttpRequest cannot load http://localhost:8088/alfresco/api/-default-/public/authentication/versions/1/tickets. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8100' is therefore not allowed access. The response had HTTP status code 403.`

I test it with other computer (same network) alfresco instance, without luck.

Could you please provide the way to avoid CORS in the app using alfresco local instance?

Kind Regards,
Alberto

**Comment by DenisVuyka** [comment]
Hello Alberto,

There are several prerequisites I had to mention in the readme, thanks for pointing out.

- You need ionic 2 (beta)
- As per `Angular 2` dependency there's a node.js constraint

>Verify that you are running at least node v4.x.x and npm 3.x.x by running node -v and npm -v in a > terminal/console window. Older versions produce errors.

I am using node v6.5.0 but may setup Travis later on to check earlier versions as well. 

- `alfresco-js-api` indeed requires `alfresco 5.2`
- You can get more details on CORS within our Angular 2 components docs, [prerequisites page] (https://github.com/Alfresco/alfresco-ng2-components/blob/master/PREREQUISITES.md)

This project is still at very early stages so more content and details to be added,

Regards,
Denys

**Comment by slaptot** [comment]
Thanks! Works like a charm!

**Comment by slaptot** [comment]
![Alt Text](http://g.recordit.co/qzmvLcjm4k.gif)
